{% set name = "allagash" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Allagash-{{ version }}.tar.gz
  sha256: 1b2b3e7cce40444d3078f0f7f791383cc03791e72922c5415c6aa94704b00781

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas >=0.23.0
    - pulp >=1.6.1
    - python >=3.6
  run_constrained:
    - geopandas >=0.4.1
    - arcgis >=1.8.2

test:
  imports:
    - allagash
    - allagash.coverage
    - allagash.problem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apulverizer/allagash
  summary: A Python spatial optimization library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://apulverizer.github.io/allagash
  dev_url: https://github.com/apulverizer/allagash

extra:
  recipe-maintainers:
    - apulverizer
